//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTasks
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public System.DateTime DueDate { get; set; }
        public int UserID { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
    }
}
